version: '3.9'

services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - praktikum

  app:
    container_name: prackicum-server-code-alchemists
    image: osoko007/prackicum-server-code-alchemists:latest
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      SERVER_PORT: 3000
      POSTGRES_DB: postgres
      CLIENT_PORT: 3000
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      YANDEX_API_URL: https://ya-praktikum.tech
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - praktikum
    tty: true

# Настройки созданной сети между сервисами
networks:
  praktikum:
    driver: bridge
