version: '3.9'

services:
  postgres:
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ./postgres.env
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - awesome

  server:
    container_name: prakticum-server
    image: prackicum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
    networks:
      - awesome

# Настройки созданной сети между сервисами
networks:
  awesome:
    driver: bridge
