version: '3.9'

services:

  postgres:
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ./postgres.env
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - praktikum

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - praktikum

  app:
    container_name: prakticum-dev
    image: prackicum-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ./postgres.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      - praktikum
    tty: true

# Настройки созданной сети между сервисами
networks:
  praktikum:
    driver: bridge

volumes:
  pgadmin-data:
